[package]
name = "lstm_with_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.33.0"
egui = "0.33.0"
egui_extras = { version = "0.33.0", features = ["datepicker"] }

chrono = { version = "0.4.42", default-features = false, features = ["clock"] }